[package]
name = "berto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
arrow = { version = "52.2", optional = false }
arrow-array = "52.2"
arrow-schema = "52.2"
futures = "0.3.31"
lancedb = "0.11.0"
rust-bert = "0.23.0"
serde_json = "1.0.132"
thiserror = "1.0.66"
tokio = { version = "1.41.0", features = ["full"] }
